spring:
  application:
    name: react-router-connect
  datasource:
    url: jdbc:mysql://localhost:3306/react_router_connect
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update      
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true


server:
  port: 8080
  
